<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;
use bedrockcloud\cloudbridge\network\RequestPacket;

class ListTemplatesRequestPacket extends RequestPacket
{

    public function getPacketName(): string
    {
        return "ListTemplatesRequestPacket";
    }

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

}