<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;
use bedrockcloud\cloudbridge\network\RequestPacket;

class ListServerRequestPacket extends RequestPacket
{

    public function getPacketName(): string
    {
        return "ListServerRequestPacket";
    }

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

}