<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;

class PlayerMovePacket extends DataPacket
{

    public $playerName;
    public $toServer;

    public function getPacketName(): string
    {
        return "PlayerMovePacket";
    }

    public function encode()
    {
        $this->addValue("packetName", $this->getPacketName());
        $this->addValue("playerName", $this->playerName);
        $this->addValue("toServer", $this->toServer);
        return parent::encode(); // TODO: Change the autogenerated stub
    }

}