<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;

class PlayerKickPacket extends DataPacket
{
    public $playerName;
    public $reason;

    public function getPacketName(): string
    {
        return "PlayerKickPacket";
    }

    public function encode()
    {
        $this->addValue("packetName", $this->getPacketName());
        $this->addValue("playerName", $this->playerName);
        $this->addValue("reason", $this->reason);
        return parent::encode(); // TODO: Change the autogenerated stub
    }

}