<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;

class PlayerMovePacket extends DataPacket {

    public string $playerName;
    public string $toServer;

    public function encode(): bool|string
    {
        $this->addValue("packetName", $this->getPacketName());
        $this->addValue("playerNames", $this->playerName);
        $this->addValue("toServer", $this->toServer);
        return parent::encode(); // TODO: Change the autogenerated stub
    }
}