<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;

class PlayerMessagePacket extends DataPacket
{
	public $playerName;
	public $value;

	public function getPacketName(): string
	{
		return "PlayerMessagePacket";
	}

	public function encode() {
        $this->addValue("packetName", $this->getPacketName());
		$this->addValue("playerName", $this->playerName);
        $this->addValue("value", $this->value);
		return parent::encode(); // TODO: Change the autogenerated stub
	}

}