<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\network\DataPacket;

class PlayerMessagePacket extends DataPacket {
	public string $playerName;
	public string $value;

	public function encode(): bool|string
    {
        $this->addValue("packetName", $this->getPacketName());
		$this->addValue("players", $this->playerName);
        $this->addValue("value", $this->value);
		return parent::encode(); // TODO: Change the autogenerated stub
	}

}