<?php

namespace bedrockcloud\cloudbridge\network\packet;

use bedrockcloud\cloudbridge\CloudBridge;
use bedrockcloud\cloudbridge\network\DataPacket;
use bedrockcloud\cloudbridge\objects\VersionInfo;

class VersionInfoPacket extends DataPacket
{

    public string $name;
    public string $author;
    public string $version;
    public string $identifier;

    public function handle(): void
    {
        $this->name = $this->data["name"];
        $this->author = $this->data["author"];
        $this->version = $this->data["version"];
        $this->identifier = $this->data["identifier"];
        CloudBridge::$versionInfo = new VersionInfo($this->name, $this->author, $this->version, $this->identifier);
        parent::handle(); // TODO: Change the autogenerated stub
    }

}