<?php

namespace bedrockcloud\cloudbridge\network\packet\response;

use bedrockcloud\cloudbridge\network\RequestPacket;

class ListTemplatesResponsePacket extends RequestPacket {
    public array $templates = [];

    public function handle(): void
    {
        $this->templates = json_decode($this->data["templates"], true);
        parent::handle(); // TODO: Change the autogenerated stub
    }
}