<?php

namespace bedrockcloud\cloudbridge\network\packet\response;

use bedrockcloud\cloudbridge\network\RequestPacket;

class ListTemplatesResponsePacket extends RequestPacket
{

    public function getPacketName(): string
    {
        return "ListTemplatesResponsePacket";
    }

    public function handle()
    {
        //var_dump(json_decode($this->data["templates"], true));
        parent::handle(); // TODO: Change the autogenerated stub
    }

}