<?php

namespace bedrockcloud\cloudbridge\network\packet\response;

use bedrockcloud\cloudbridge\network\RequestPacket;

class ServerStopResponsePacket extends RequestPacket {
    private bool $success;
    private int $failureId = -1;
    private ?string $serverInfoName = null;

    public function handle()
    {
        $this->success = $this->data["success"];
        if (!$this->success) {
            $this->failureId = $this->data["failureId"];
        } else {
            $this->serverInfoName = $this->data["serverInfoName"];
        }
        parent::handle(); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function isSuccess(): bool
    {
        return $this->success;
    }

    /**
     * @return int
     */
    public function getFailureId(): int
    {
        return $this->failureId;
    }

    public function getServer(): ?string
    {
        return $this->serverInfoName;
    }
}