<?php

namespace bedrockcloud\cloudbridge\network\packet\response;

use bedrockcloud\cloudbridge\network\RequestPacket;

class StartTemplateResponsePacket extends RequestPacket {
    private bool $success = false;
    private int $failureId = -1;
    private array $template = [];

    public function handle()
    {
        $this->success = $this->data["success"];
        if (!$this->success) {
            $this->failureId = $this->data["failureId"];
        } else {
            $this->template = json_decode($this->data["template"], true);
        }
        parent::handle(); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function isSuccess(): bool
    {
        return $this->success;
    }

    /**
     * @return int
     */
    public function getFailureId(): int
    {
        return $this->failureId;
    }

    /**
     * @return array
     */
    public function getTemplate(): array
    {
        return $this->template;
    }
}