<?php

namespace bedrockcloud\cloudbridge\network\packet\proxy;


use bedrockcloud\cloudbridge\listener\cloud\ProxyPlayerQuitEvent;
use bedrockcloud\cloudbridge\network\DataPacket;

class ProxyPlayerQuitPacket extends DataPacket {

    public function handle()
    {
        $ev = new ProxyPlayerQuitEvent($this->data["playerName"]);
        $ev->call();
        parent::handle(); // TODO: Change the autogenerated stub
    }

}