<?php

namespace bedrockcloud\cloudbridge\network\packet\proxy;

use bedrockcloud\cloudbridge\listener\cloud\ProxyPlayerJoinEvent;
use bedrockcloud\cloudbridge\network\DataPacket;

class ProxyPlayerJoinPacket extends DataPacket {

    public function handle(): void
    {
        $ev = new ProxyPlayerJoinEvent($this->data["playerName"]);
        $ev->call();
        parent::handle(); // TODO: Change the autogenerated stub
    }
}