<?php

namespace bedrockcloud\cloudbridge\network\packet\request;

use bedrockcloud\cloudbridge\network\RequestPacket;

class ListCloudPlayersRequestPacket extends RequestPacket
{

    public function getPacketName(): string
    {
        return "ListCloudPlayersRequestPacket";
    }

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

}