<?php

namespace bedrockcloud\cloudbridge\network\packet\request;

use bedrockcloud\cloudbridge\network\RequestPacket;

class StopTemplateRequestPacket extends RequestPacket {
    const FAILURE_TEMPLATE_EXISTENCE = 0;
    const FAILURE_TEMPLATE_NOT_RUNNING = 1;

    public function getPacketName(): string
    {
        return "StopTemplateRequestPacket";
    }

    public function encode()
    {
        return parent::encode(); // TODO: Change the autogenerated stub
    }
}